import os

PROJECT_ID = "your-project-id"
REGION = "us-central1"

NVD_API_KEY = os.getenv("")

INDEX_ID = "YOUR_INDEX_ID"
ENDPOINT_ID = "YOUR_ENDPOINT_ID"
DEPLOYED_INDEX_ID = "YOUR_DEPLOYED_INDEX_ID"
